# Generated by Django 5.2.7 on 2026-03-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
