# Generated by Django 5.2.7 on 2026-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
