# Generated by Django 5.2.7 on 2026-03-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='news/attachments/'),
        ),
    ]
