# Generated by Django 5.2.7 on 2026-03-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], max_length=10),
        ),
    ]
