# Generated by Django 5.2.7 on 2026-04-02 16:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
