# Generated by Django 5.2.7 on 2026-04-03 04:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='team'),
        ),
    ]
