# Generated by Django 5.2.7 on 2026-04-03 04:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
        migrations.AlterField(
            model_name='news',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='news/attachments'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='news'),
        ),
    ]
