# Generated by Django 5.2.7 on 2026-04-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='position',
        ),
    ]
