# Generated by Django 5.2.7 on 2026-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_joinrequest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
