# Generated by Django 5.2.7 on 2026-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_joinrequest_email_joinrequest_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
