# Generated by Django 5.2.7 on 2026-04-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_joinrequest_otp_joinrequest_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
